### ISSUE TITLE
User Control for WanIpConnection is greyed out

### ISSUE THREAD

**Issue by RoSchmi** [Rans4ckeR/RS.Fritz.Manager#18]
User Control for WanIpConnection is greyed out. I think it shouldn't be on my Fritzbox Cable.
When I click the 'LogIn' button I see that 2 exceptions are thrown:
Ausnahme ausgelöst: "System.ArgumentOutOfRangeException" in RS.Fritz.Manager.UI.dll
Ausnahme ausgelöst: "System.ArgumentOutOfRangeException" in System.Private.CoreLib.dll

I didn't try to find the reason. Perhaps you will know it at once.

**Comment by Rans4ckeR** [comment]
@RoSchmi can you test again?

**Comment by RoSchmi** [comment]
WanIpConnection works now. But WanDslInterfaceConnection and DSL diagnostic test can be started on my Fritzbox Cable (should be inactivated) and throw exceptions.

**Comment by Rans4ckeR** [comment]
> WanIpConnection works now. But WanDslInterfaceConnection and DSL diagnostic test can be started on my Fritzbox Cable (should be inactivated) and throw exceptions.

@RoSchmi can you try this again using the develop branch?

**Comment by RoSchmi** [comment]
@Rans4ckeR Works now as expected. And so many new functions in the meantime. Great!!
