### ISSUE TITLE
Method 'whenAllTask' in 'TaskExtensions.cs' throws exception 

### ISSUE THREAD

**Issue by RoSchmi** [Rans4ckeR/RS.Fritz.Manager#2]
First let me say thanks for the valuable code,

I was able to compile and run your application on a Windows10 PC, Visual Studio 2022, Framework net6.0.
Discovering the Gatway Devices, selecting the Device (Infos are shown), selecting a user and entering a User password worked as expected.
But then, when I click the 'Device Information' tab and click the 'DeviceInfo' button again an exception is thrown in 'TaskExtensions.cs' line 42 and the applcation stops.

![FritzManagerException](https://user-images.githubusercontent.com/24595510/148234275-585c296b-6cea-4a6b-9b58-19e17945657c.png)

Best regards
RoSchmi

**Comment by Rans4ckeR** [comment]
@RoSchmi can you update to the latest commit and copy the entire exception text?

**Comment by RoSchmi** [comment]
Hi, thanks for your fast response.
For your information I'm using a:  FRITZ!BOX 6490 Cable (lgi)
In the meantime it happened (I don't know why) that it did not longer throw an exception when I click on the 'DeviceInfo' button. (may be that I had a firmware update of the Fritzbox today) 
I now use your last commit from today.
The 'LanConfigSecurity' button and the 'Layer3Forwardin' button work fine as well.
However with the 'WanDslInterfaceSecurity' button I get the exception.
I changed the code of 'TaskExtensions.cs' a little bit (to set a breakpoint)  to:

`public static async Task WhenAllSafe(IEnumerable<Task> tasks)
        {
            Task whenAllTask = Task.WhenAll(tasks);

            try
            {
                await whenAllTask;

                return;
            }
            catch (System.Exception ex)
            {
                string exMessage = ex.Message;
                // Ignore individual task exceptions
            }

#pragma warning disable CS8597 // Thrown value may be null.
            //throw whenAllTask.Exception;
#pragma warning restore CS8597 // Thrown value may be null.
        }`

At the breakpoint in the catch I see the following exception:

![ErrorMessage](https://user-images.githubusercontent.com/24595510/148267894-a4f91af3-7048-45c6-b2a1-4c7dcc926c59.png)

When I step over the 'Info' template appears but the values are empty.

![Info](https://user-images.githubusercontent.com/24595510/148267977-1728ead2-a67f-4648-911a-439820fdd911.png)

When I click the 'WanPppConnection' button I get an exception too:

![WanPppConnectionError](https://user-images.githubusercontent.com/24595510/148268052-9de07812-7b4f-4ef7-b4be-7028135363cb.png)

However, as I'm not familiar with the stuff like 'Layer3Forwarding' and 'WanPppConnection' I do not know what I should expect.
Perhaps you could give a short explanation about the usefulness of these functions in your ReadMe.

**Comment by Rans4ckeR** [comment]
@RoSchmi the services WANPPPConnection and WANDSLInterfaceConfig are not supported by your model. The exception is your device responding with an UPnPError for this reason. The buttons have a tooltip with some more information. Basically these 2 services are only supported by DSL models.
It is possible to detect which services the device supports and then disable these buttons but the application does not do this currently.

**Comment by RoSchmi** [comment]
Ah.. 'das ist schade!'. Do you think that I could implement similar functions for my Fritzbox cable as a supplement to your application without too much effort or would it be advisable to use another C# library (can you evtl. give a recommendation ?)
Thanks for your support

**Comment by Rans4ckeR** [comment]
@RoSchmi It should be relatively easy to add more services. They are listed under "Apps / TR-064" here: [Entwicklungssupport](https://avm.de/service/schnittstellen/). Depending on what you need you could perhaps have a look at WANIPConnection and/or WANCommonInterfaceConfig.

**Comment by RoSchmi** [comment]
@Rans4ckeR I implemented some functions of the 'WANCommonInterfaceConfig' service. If you are interested, I could prepare a pull request.
Your code is really a good example to learn the modern patterns.
