### ISSUE TITLE
In Hosts service Index numbers of HostLists and GenericHostEntry do not match

### ISSUE THREAD

**Issue by RoSchmi** [Rans4ckeR/RS.Fritz.Manager#23]
In the list the indices start with '1' in GenericHostEntry they start with '0'.

**Comment by Rans4ckeR** [comment]
@RoSchmi the devicehostlist.xml as coming from the device indeed starts with index 1 while the service GetGenericHostEntry request is 0 based.
There is no guaranteed mapping between the 2. When requesting GetGenericHostEntry with the same index several times in a row I get a different host in the response.

**Comment by RoSchmi** [comment]
> When requesting GetGenericHostEntry with the same index several times in a row I get a different host in the response.
I cannot confirm your observation on my Fritzbox. When I enter an index number several times, I always get the same host as response. To get a host from the Hostslist with a certain index I have to enter this index -1.

**Comment by Rans4ckeR** [comment]
@RoSchmi It's still possible to retrieve GetGenericHostEntry entries using a raw unaltered value (0 based) but I added automatic retrieval of all entries. When retrieving all the GetGenericHostEntry entries at the same time as retrieving the xml list they always seem to match at my end.
