### ISSUE TITLE
Not able to get additional action 'GetGenericHostEntry' to Hosts service working

### ISSUE THREAD

**Issue by RoSchmi** [Rans4ckeR/RS.Fritz.Manager#4]
I'm trying to add 'GetGenericHostEntry' to Hosts service. As with your library I was not successful I tried another library (FBoxAPI) andwith this API I got it working.
With 'RS.FritzManager.Domain' my Fritzbox cable returns a fault code and complains of an invalid action.
To see the real requests and resonses I used Fiddler to see the network traffic. In the pictures below you can see the requests and responses of both libraries but I have no idea why it doesn't work with your library. 
 
![Traffic_RS Fritz Manager Domain](https://user-images.githubusercontent.com/24595510/150124737-7510c950-65dc-4047-9577-9697b72d07c8.png)
*

*

*

![Traffic_FBoxAPI](https://user-images.githubusercontent.com/24595510/150124767-92f51352-09a6-4573-b798-76f5625593f4.png)

Do you see a reason?

**Comment by Rans4ckeR** [comment]
@RoSchmi can you commit your code in your repository?

**Comment by RoSchmi** [comment]
@Rans4ckeR Thanks for your fast reply. The code to try is in the branch devRoSchmiPr2. Click on the hosts button to start the actions.

**Comment by Rans4ckeR** [comment]
@RoSchmi the operation contract is incorrect:
`[OperationContract(Action = "urn:dslforum-org:service:Hosts:1#X_AVM-DE_GetGenericHostEntry")]`
should be
`[OperationContract(Action = "urn:dslforum-org:service:Hosts:1#GetGenericHostEntry")]`

This value is set in the headers not in the body, so we can't see this mistake in your screenshots.

**Comment by RoSchmi** [comment]
@Rans4ckeR thanks, works now. Should have asked earlier. If you agree I'll prepare a pull request for the new actions.

**Comment by Rans4ckeR** [comment]
@RoSchmi sure go ahead.
